server:
  servlet:
    context-path: /api
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: on
  sql:
    init:
      mode: always
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  docker:
    compose:
      lifecycle-management: start_only


springdoc:
  swagger-ui:
    path: /docs

