INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (1, 12.5, 9.4, 'Протромбиновое время', 'сек');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (2, 1.2, 0.8, 'МНО/INR', null);
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (3, 10, 70, 'Протромбин по Квику', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (4, 3.93, 2, 'Фибриноген', 'г/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (5, 36.5, 21.1, 'АЧТВ', 'сек');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (6, 1.2, 0.75, 'АЧТВ (ratio)', 'сек');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (7, 24.9, 15.8, 'Тромбиновое время', 'сек');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (8, 83, 64, 'Общий белок', 'г/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (9, 52, 35, 'Альбумин', 'г/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (10, 5, 0, 'С-реактивный белок', 'мг/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (11, 7.2, 2.8, 'Мочевина', 'ммоль/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (12, 96, 58, 'Креатинин', 'мкмоль/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (13, 357, 154.7, 'Мочевая кислота', 'мкмоль/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (14, 35, 0, 'Аланинаминотрансфераза (АЛТ)', 'Ед/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (15, 35, 0, 'Аспартатаминотрансфераза (АСТ)', 'Ед/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (16, 145, 0, 'Креатинкиназа (КФК)', 'МЕ/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (17, 21, 5, 'Билирубин общий', 'мкмоль/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (18, 38, 0, 'Гамма-глутамилтрансфераза (ГГТ)', 'МЕ/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (19, 98, 33, 'Щелочная фосфатаза (ЩФ)', 'Ед/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (20, 5, 0, 'Холестерин общий', 'ммоль/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (21, 1.5, 0, 'Триглицериды', 'ммоль/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (22, 5.1, 3.5, 'Калий', 'ммоль/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (23, 145, 136, 'Натрий, Na+', 'ммоль/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (24, 112, 98, 'Хлор, Cl+', 'ммоль/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (25, 0.15, 0, 'Общий белок мочи', 'ммоль/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (26, 11, 4.5, '(WBC) Лейкоциты', '10*9/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (27, 5.1, 3.8, '(RBC) Эритроциты', '10*12/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (28, 155, 117, '(HGB) Гемоглобин', 'г/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (29, 45, 35, '(HCT) Гематокрит', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (30, 100, 81, '(MCV) Ср.объем эритроцита', 'фл');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (31, 34, 27, '(MCH) Среднее содержание гемоглобина в эритроците', 'пг');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (32, 356, 314, '(MCHC)Ср. концентрация гемоглобина в эритроците', 'г/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (33, 54, 37, '(RDW-SD)Ширина распределения эритроцитов', 'фл');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (34, 14.4, 11.6, '(RDW-CV)Ширина распределения эритроцитов', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (35, 5, 0, 'Отн количество нормобластов', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (36, 0.03, 0, 'Абс количество нормобластов', '10*9/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (37, 400, 150, '(PLT) Тромбоциты', '10*9/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (38, 16.7, 9.7, '(PDW) Ширина распределения тромбоцитов по объему', 'фл');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (39, 43, 13, '(P-LCR) Процент крупных тромбоцитов', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (40, 0.39, 0.18, '(PCT) Общий объем тромбоцитов в крови (тромбоцитокрит)', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (41, 6.13, 1.56, '(NEU#) Нейтрофилы', '10*9/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (42, 3.74, 1.18, '(LYM#) Лимфоциты', '10*9/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (43, 1.1, 0.4, '(MONO#) Моноциты', '10*9/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (44, 0.4, 0.04, '(EOS#) Эозинофилы', '10*9/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (45, 0.08, 0.01, '(BAS#) Базофилы', '10*9/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (46, 72, 47, '(NEU%) Нейтрофилы', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (47, 12, 5, '(MONO%) Моноциты', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (48, 37, 19, '(LYM%) Лимфоциты', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (49, 5, 1, '(EOS%) Эозинофилы', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (50, 1, 0, '(BAS%) Базофилы', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (51, 66.1, 55.8, 'Альбумин %', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (52, 4.9, 2.9, 'Альфа-1-глобулин %', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (53, 11.8, 7.1, 'Альфа-2-глобулин %', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (54, 7.2, 4.7, 'Бета-1-глобулин %', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (55, 6.5, 3.2, 'Бета-2-глобулин %', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (56, 18.8, 11.1, 'Гамма глобулин %', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (57, 18.8, 11.1, 'Гамма глобулин %', '%');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (58, 47.6, 40.2, 'Альбумин 2', 'г/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (59, 3.5, 2.1, 'Альфа-1-глобулин', 'г/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (60, 8.5, 5.1, 'Альфа-2-глобулин', 'г/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (61, 5.2, 3.4, 'Бета-1-глобулин', 'г/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (62, 4.7, 2.3, 'Бета-2-глобулин', 'г/л');
INSERT INTO public.reference (id, max_value, min_value, name, unit) VALUES (63, 13.5, 8, 'Гамма глобулин', 'г/л');
